In [3]:
import numpy as np

def convolve(image, kernel):
    """
   convolve algorithm without padding and striding.

    Parameters:
    - image (numpy.ndarray): The original image matrix (6x6).
    - kernel (numpy.ndarray): The filter (or kernel) to apply (3x3).

    Returns:
    - numpy.ndarray: The resulting image after convolution.
    """
    # Flip the kernel horizontally and vertically
    kernel_flipped = np.flipud(np.fliplr(kernel))
    
    # Calculate the dimensions of the output matrix
    output_height = image.shape[0] - kernel_flipped.shape[0] + 1
    output_width = image.shape[1] - kernel_flipped.shape[1] + 1
    
    # Initialize the output matrix with zeros
    output = np.zeros((output_height, output_width))
    
    # Perform the convolution operation
    for row in range(output_height):
        for col in range(output_width):
            # Element-wise multiplication (Hadamard product) and summation
            output[row, col] = np.sum(
                image[row:row+kernel_flipped.shape[0], col:col+kernel_flipped.shape[1]] * kernel_flipped
            )
    
    return output

# 6x6 image
image = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18],
    [19, 20, 21, 22, 23, 24],
    [25, 26, 27, 28, 29, 30],
    [31, 32, 33, 34, 35, 36]
])

# 3x3 filter
kernel = np.array([
    [-1, -2, -1],
    [0,  0,  0],
    [1,  2,  1]
])

# Perform convolution
result = convolve(image, kernel)
print("Original Image (6x6):\n", image)
print("\nFilter (3x3):\n", kernel)
print("\nConvolved Image (4x4):\n", result)


Original Image (6x6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Filter (3x3):
 [[-1 -2 -1]
 [ 0  0  0]
 [ 1  2  1]]

Convolved Image (4x4):
 [[-48. -48. -48. -48.]
 [-48. -48. -48. -48.]
 [-48. -48. -48. -48.]
 [-48. -48. -48. -48.]]
